version: '3.8'

services:
  my-task-board-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-task-board
    container_name: my-task-board
    restart: on-failure
    ports:
      - 4200:80
